import "../styles/global.css";
import Navigation from "../components/navigaion"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Navigation />
        {children}</body> 
    </html>
  )
}
  

// About 컴포넌트가 레이아웃 컴포넌트의 children이 되는 것이다. 가령 <layout> <aboutus/> </layout> 
// 어떤 페이지로 이동할때마다 이 레이아웃 컴포넌트가 렌더링 되고 내가 가려는 페이지가 이런식으로 children이 되는 것이다. 
// 해당 페이지는 이런 식으로 layout 컴포넌트의 children prop이 될것이다. 그래서 레이아웃이 자동으로 생성되는 것이 이유이다. 
// 어떤 페이지가 들어가든 네비게이션바가 보이게 할 수 있다.
// about page만을 위한 레이아웃을 만들 수 있다. 
